import React from 'react'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

import { Navbar } from './Navbar'
import { Footer } from './Footer'

export const Layout = ({children}) => {
  return (
    <div className={styles.pageContainer}>
    <div className={styles.contentWrap}>
        <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main> 
      {children}

      </main>
      <Footer />
    </div>
      </div>
    )
}
